apiVersion: v1
kind: Service
metadata:
  name: kube-struts-svc
spec:
  type: LoadBalancer
  ports:
    - port: 8080
 selector:
    app: kube-struts-pod
 
---
 
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-struts-pod
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-struts-pod
    spec:
      containers:
        - name: kube-struts-pod
          image: dieterreuter/struts
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: docker-sock
              readOnly: false
      restartPolicy: Always
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
            
